#pragma once

#include <bits/stdc++.h>
#include <colmap/base/camera_models.h>
#include <colmap/base/image.h>

using namespace std;
using namespace colmap;

class CLIntrinsics
{
public:
    int width, height;
    double fx, fy;
    double cx, cy;
    double k1, k2, p1, p2;

    // an ideal pinhole camera
    CLIntrinsics(int width, int height, double focalLen);

	CLIntrinsics(int width, int height, double fx, double fy, double cx, double cy, double k1 = 0, double k2 = 0, double p1 = 0, double p2 = 0);

    CLIntrinsics(int width, int height, vector<double> params);


    double fovX();
    double fovY();

	// loads cameras from the cameras.txt file generated by colmap
	static vector<CLIntrinsics> loadCameras(string path);
};