#pragma once

#include <bits/stdc++.h>
#include <colmap/base/camera_models.h>
#include <colmap/base/image.h>

using namespace std;
using namespace colmap;

class RadialCamera
{
public:
	vector<double> params;

	RadialCamera(double width, double height, double focalLen, double distortion);

	// loads cameras from the cameras.txt file generated by colmap
	static vector<RadialCamera> loadCameras(string path);
};